### ISSUE TITLE
关于检测镜头前的静态遮挡的问题

### ISSUE THREAD

**Issue by sycamore27** [Junhua-Liao/VSOD#1]
作者您好，非常感激您开源这么棒的工作！我在自己拍摄的视频上测试效果时发现一个问题想向您请教：
当人物在镜头前快速走过并发生遮挡时，该算法能敏锐地检测到。但当遮挡人在镜头前静止停留了一段时间（相对整个视频停留时间不长），该算法对于这样的静态遮挡好像并不能检测到。想请问下该算法有考虑处理这样的情况吗？也想请教对于实现这个部分有改进建议吗？期待您的回复，感谢！

**Comment by Junhua-Liao** [comment]
感谢你对我们的工作感兴趣。

在《A Video Shot Occlusion Detection Algorithm Based on the Abnormal Fluctuation of Depth Information》中的第VI章节（Limitation and Future Work）中我们有讨论这个问题。我们现有的算法思路是基于遮挡物闯入镜头导致画面突变设计的，但是如果遮挡物闯入镜头后移动缓慢甚至静止，算法在没有捕捉到画面突变的情况下会以为镜头处于正常状态导致漏检。

目前想到的一种解决方案是先判断画面中的主角，根据主角是否被遮挡来做进一步判断。

**Comment by sycamore27** [comment]
收到，感谢您及时的回复，留意到SoU是以每秒为分隔计算各帧的情况，使得该方法仅对突变画面有效。
还想请教下您之前的工作《A Light Weight Model for Video Shot Occlusion Detection》，该文章提出基于深度学习的方法也有同样的局限，只能检测到遮挡物进入和离开时有遮挡，对于静止状态无法检测。也是因为Occlusion Loss设计的原因吗？

**Comment by Junhua-Liao** [comment]
《A Light Weight Model for Video Shot Occlusion Detection》中的方法是基于VSOD v1.0数据集训练的，可能是因为该数据集中缺乏静态遮挡，所以对静态遮挡的检测性能较差。
